development: &defaults
  database: 'js_host_development'
  adapter: mysql
  host: localhost
  user: foo
  password: bar
  encoding: UTF8

production:
  <<: *defaults

test:
  database: 'db/test.sqlite3'
  adapter: sqlite3
  pool: 5
  timeout: 5000